### ISSUE TITLE
you put the wrong example

### ISSUE THREAD

**Issue by arslion** [fusioncharts/php-wrapper#1]
you put the wrong example of php code of Loading data from MySQL here on this page: http://www.fusioncharts.com/php-charts/

There is an opened if statement with no close braces. Update your website.

**Comment by adotg** [comment]
@arslion Thanks for pointing it out. Cheers.
@sguha-fc  is taking it up and is done. We are going to update it once all the process is completed.

**Comment by sguha-work** [comment]
@arslion We have updated our website, If you got any problem in using FusionCharts with our PHP-wrapper please let us know we will be glad to help you.

**Comment by arslion** [comment]
Good work. Keep it up!
