### ISSUE TITLE
Empty Page

### ISSUE THREAD

**Issue by LightsOnHudson** [fusioncharts/php-wrapper#10]
Hello, 
I have all the required files, the latest engine and themes and js files loaded.

yet the page still displays blank with the examples you have provided.

Any help is greatly appreciated.

**Comment by suvradip** [comment]
Hi,
 Please provide your source code if possible so we can debug for you or otherwise you can try this sample which is attached bellow. Anyway which sample you are trying ?
[php-sample.zip](https://github.com/fusioncharts/php-wrapper/files/749667/php-sample.zip)

**Comment by rahul-kr2000** [comment]
Quite an old issue. No reply received from the user. Hence closing this issue. For more discussion please write to support@fusioncharts.com.
