### ISSUE TITLE
Not able to remove FusionChartsXT Trial lable

### ISSUE THREAD

**Issue by ikishanoza** [fusioncharts/php-wrapper#11]
i using it in my local server try to remove FusionCharts XT Trial lable but cant. Please help me out

**Comment by PallabDV** [comment]
Hi Kishanlos007, FusionCharts is a proprietary software. The trial version has the watermark embedded. If you want to remove the watermark, please procure a [license](http://www.fusioncharts.com/buy/).

**Comment by DNTech** [comment]
```
    <style type="text/css">
        g[class$='creditgroup'] {
             display:none !important;
        }
    </style>
```

This worked for me and I guess it's simple and will work for all.

You can make it even more specific.

```
    <style type="text/css">
        g[class^='raphael-group-'][class$='-creditgroup'] {
             display:none !important;
        }
    </style>
```

**Enjoy illegality ;)**

**Comment by ikishanoza** [comment]
Thanks it works 👍  @DNTech

**Comment by djangorobert** [comment]
nice!

**Comment by thotasatyasri** [comment]
where to place the code

**Comment by thotasatyasri** [comment]
I just tried this..but not working

**Comment by arshita-kakkar** [comment]
Thanks, works great!

**Comment by rahul-kr2000** [comment]
Guys, to remove the watermark, you'll have to procure the licensed version of the product. Removing the watermark using some code/hacks are illegal.

**Comment by VamanPatel** [comment]
**_not working_**

**Comment by joankent** [comment]
not working
