### ISSUE TITLE
Unable to find the container DOM element 

### ISSUE THREAD

**Issue by suraj050** [fusioncharts/php-wrapper#2]
I had use this code:
<html>
<head>
    <script type="text/javascript" src="js/fusioncharts.js"></script>
    <script type="text/javascript" src="js/themes/fusioncharts.theme.ocean.js"></script>
</head>
<body>
    <?php
        include("fusioncharts.php");
        $columnChart = new FusionCharts(
                "column2d", 
                "exmpl" , 
                "600", 
                "400", 
                "chart-1", 
                "json", 
                '{  
                   "chart":
                   {  
                      "caption":"Harry\'s SuperMart",
                      "subCaption":"Top 5 stores in last month by revenue",
                      "numberPrefix":"$",
                      "theme":"ocean"
                   },
                   "data":
                   [  
                      {  
                         "label":"Bakersfield Central",
                         "value":"880000"
                      },
                      {  
                         "label":"Garden Groove harbour",
                         "value":"730000"
                      },
                      {  
                         "label":"Los Angeles Topanga",
                         "value":"590000"
                      },
                      {  
                         "label":"Compton-Rancho Dom",
                         "value":"520000"
                      },
                      {  
                         "label":"Daly City Serramonte",
                         "value":"330000"
                      }
                   ]
            }');
        // Render the chart
        $columnChart->render();
    ?>
</body>
</html>

Got the following error.

**Comment by sguha-work** [comment]
You have to provide a chart container inside your page. Normally it is a div. You have already provided the chart container id as "chart-1" inside the constructor parameter. So adding the following div to the page `<div id="chart-1"></div>` will solve the problem
