### ISSUE TITLE
Missing containerBackgroundOpacity and styles

### ISSUE THREAD

**Issue by kikosoft** [fusioncharts/php-wrapper#4]
Hi,

It seems the PHP wrapper has been renewed. The old one had options for setting the 'containerBackgroundOpacity' and adding styles, this one doesn't. More might be missing, which I haven't noticed yet.
Any plan on making the PHP wrapper more complete? (the wrapper might be open source, but it is needed for a product that I bought).

**Comment by badcrocodile** [comment]
I was wondering the same thing. We're missing a lot of options that are available via other means, such as dataLoadStartMessage, LoadMessage, etc.

**Comment by rahul-kr2000** [comment]
Support for Messages and Events are already added.
