### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by MPParsley** [fusioncharts/php-wrapper#6]
Could you provide the wrapper as a PHP library using a Composer package?

https://getcomposer.org/doc/01-basic-usage.md
https://packagist.org/about

**Comment by GenesisCraig** [comment]
Has anybody looked into this?  It would be a great way for PHP users to be able to keep up with releases.  Good advertising too. ;-)

**Comment by rahul-kr2000** [comment]
We have noted it down and will work on it.
