### ISSUE TITLE
Empty display after setting up all the requirements

### ISSUE THREAD

**Issue by gosfem** [fusioncharts/php-wrapper#7]
I have downloaded every neccessaries documents and connect them according to the instructions. however, when I load my browser, it show an empty page.

I want to fetch data from mysql database .

Thanks

**Comment by suvradip** [comment]
Hi,
Thanks for your query.
The blank page or empty page may occur if the **fusioncharts.js** library files are not loaded properly in your browser. Please make sure that you have added the **fusioncharts.js** file in your page properly.

we've updated our repository with new chart-samples using database, hope this will help you to start with your application.

**Comment by rahul-kr2000** [comment]
Quite an old issue. No reply received from the user. Hence closing this issue. For more discussion please write to support@fusioncharts.com.
